[project]
name = "bids_prov"
version = "0.2.0"
description = "Python utilities to handle provenance in BIDS datasets."
authors = [
    { name = "Camille Maumet" },
    { name = "Satrajit Ghosh" },
    { name = "Stefan Appelhoff" },
    { name = "Chris Markiewicz" },
    { name = "Yaroslav Halchenko" },
    { name = "Jean-Baptiste Poline" },
    { name = "Rémi Adon" },
    { name = "Hermann Courteille" },
    { name = "Thomas Betton" },
    { name = "Cyril Regan" },
    { name = "Boris Clénet" }
]
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Medical Science Apps."
]
dependencies = [
    "graphviz>=0.20.3",
    "rdflib>=7.0.0",
    "rdflib-jsonld>=0.6.2",
    "requests>=2.32.3",
    "prov[graph]>=2.0.0",
    "pydot>=2.0.0",
    "pyld>=2.0.4",
    "pybids>=0.20.0"
]

[dependency-groups]
dev = [
    "black>=24.4.2",
    "markdownify>=0.12.1",
    "pre-commit>=3.7.1"
]
tests = [
    "pytest>=8.4.2",
    "pytest-cov>=5.0.0"
]

[project.scripts]
bids_prov = "bids_prov:entry_point"

[build-system]
requires = ["setuptools>=78.1.0", "wheel>=0.45.1"]
build-backend = "setuptools.build_meta"
